version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pl-client
    networks:
      - client_net
  
  client:
    restart: always
    depends_on:
      - db
    build: ./
    ports:
      - 3000:3001
    environment:
      - DATABASE_URL="postgresql://postgres:postgres@localhost:5432/pl-client?schema=public"
    networks:
      - client_net

networks:
  client_net: